#!/bin/sh -e
# $Id$

. /usr/share/debconf/confmodule

if [ "$1" = "install" -o "$1" = "upgrade" ]; then
        if ! id -g pykota > /dev/null 2>&1 ; then
                addgroup --system pykota
        fi
        if ! id -u pykota > /dev/null 2>&1 ; then
                adduser --system --home /etc/pykota --ingroup pykota pykota
                chsh -s /bin/sh pykota
        fi
fi

exit 0
