#!/bin/sh -e
# $Id$

. /usr/share/debconf/confmodule

/bin/chown -R pykota.pykota ~pykota
/bin/chmod 0640 ~pykota/pykota.conf
/bin/chmod 0600 ~pykota/pykotadmin.conf
/bin/chmod 0700 /usr/share/pykota/cupspykota

exit 0
