#!/bin/sh -e
# $Id$

. /usr/share/debconf/confmodule

if [ "$1" = "upgrade" ]; then
        chown -R pykota.pykota ~pykota
        chmod 640 ~pykota/pykota.conf
        chmod 600 ~pykota/pykotadmin.conf
fi

exit 0
