#!/bin/sh -e
# $Id$

. /usr/share/debconf/confmodule

if [ "$1" = "install" ]; then
        chown -R pykota.pykota ~pykota
        chmod 0640 ~pykota/pykota.conf
        chmod 0600 ~pykota/pykotadmin.conf
	chmod 0700 /usr/share/pykota/cupspykota
fi

exit 0
